---
title: "CRG_CARstratum2^2"
author: "anonymous"
output: pdf_document
---
# Libraries
```{r}
library(igraph)
library(matrixStats)
```

# Basic Setup
```{r}
n=200 

#define CRG(complete random graph) 
PP_dense=0.05 #between probability of any two units in a network.

#define CUG
#prior 
beta_alpha=1
beta_beta=50 
U_b=6 #control the influence from neighbor
b_prior=0.1 #0.1(0.01) #control the shape (e.g. clustering) of the network 
                       #control the dense of generated network
pa=0 #lower bound when continuous unobserved has largest distance
pb=0.1 #average become friend probability
KnownCov=FALSE
CRGraph=T # whether run design on complete random graph
Z_sd=0.1
```

# Link determine function
```{r}
#determine connected probability between i and j
determine<-function(a,b,covIndex, ranii,ranjj){
   #the closer a and b, the smaller return
  return(   
    min(covIndex*(ranii*ranjj*pb*(1-((a-b)/(2*U_b))^2)^2+pa), 1)
    )
}
```

# Generate whole network
```{r}
generate_adjacent2<-function(UU,XX1,XX2){
  adj=matrix(rep.int(0, n*n), n, n)
  ran=rep(1,n)
  for (i in c(1:n)){
    for (j in c(i:n)) {
      if(XX1[i]==XX1[j] & XX2[i]==XX2[j]){
        covInput=1}else if(XX1[i]!=XX1[j] & XX2[i]!=XX2[j]){
        covInput=0.5}else{
        covInput=0.25}
  
      covInput=ifelse(KnownCov, covInput,1)
      I_p=rbinom(1,1,determine(UU[i],UU[j],covInput, ran[i], ran[j]))
      adj[i,j]=I_p
      adj[j,i]=I_p
    }
  }
  return(adj)
  }
```

# Randomization algorithm setting
```{r}
N=1000 #repeat

#define observed cov
num_cov=2

#design setting
q=0.9 #CAR assignment probability *0.9 # CR: 0.5


w=1 #w=0/(n*n)
w_o=0.3
w_m=0.1
w_s=0.5

#define true model parameter
mu1=0 # Treatment effect
mu0=1 # baseline, when there is no control

gamma_X1=1 #1 #pure cov coefficients
gamma_X2=1 #1 #pure cov coefficients
gamma_X1X2=4
Error_sd=1

# define network imbalance measure
flag_imb=1 #==1 new measure; !=1 old measure
imbm=function(i,flag) {
  if (flag==1){
    return(sum(((1/i)*(1-2*t[1:i])%*%Ad[1:i,1:i]*t[1:i])^2))
  }else{
    return(sum(((1/i)*(1-2*t[1:i])%*%Ad[1:i,1:i])^2))
  }
}
```

# Randomization algorithm start
```{r}
  IMM=NULL
  IMM_net=NULL
  IMM_cov=NULL
  
  overall_diff=NULL
  ddd_1x_diff=NULL
  ddd_x0_diff=NULL
  ddd_s11_diff=NULL
  ddd_s00_diff=NULL 

  Beta_G=NULL

for (k in 1:N) {
      
  #Create known covaruates
  dd=t(rmultinom(n,1,c(0.1,0.2,0.3,0.4)))
  ddd=cbind((dd[,1]+dd[,3]),(dd[,1]+dd[,2])) 
  X1=dd[,1]+dd[,3]
  X2=dd[,1]+dd[,2] 
  
  #create network based on both known and unknown covariates 
  U=2*(rbeta(n,b_prior,b_prior)-0.5)*U_b #generate unobserved cov
  
  if(CRGraph){
    Ad=erdos.renyi.game(n,PP_dense,directed = FALSE,loops = TRUE)
    Ad=as_adjacency_matrix(Ad, type = "both")
  }else{
    Ad=generate_adjacent2(U, X1, X2)
  }
  
  ##start Algorithm## 
  t=NULL
  m=NULL
  im=NULL
  im_net=NULL
  im_cov=NULL
  
  o_diff=NULL
  dd_1x=NULL
  dd_x0=NULL
  dd_s11=NULL
  dd_s00=NULL  
  
  t[1]=rbinom(1,1,0.5)
  
  for (i in 2:n) {
    
    d_1=NULL
    TF=NULL
    dd_1=NULL
    dd_0=NULL
    TF11=NULL
    TF10=NULL
    TF01=NULL
    TF00=NULL
    
    d_o=2*sum(t[1:(i-1)])-(i-1) # overall difference
    
    for (j in 1:num_cov) {
      d_1[j]=2*sum(t[ddd[1:(i-1),j]==ddd[i,j]])-sum(ddd[1:(i-1),j]==ddd[i,j])  # margin difference D(j,1), ddd[1:i,j]==1 gives True/False of ith unit equal 1 of margin j.
    }

    for (l in 1:(i-1)) {
      TF[l]=all(ddd[l,]==ddd[i,])
    }

    d_s=sum(2*t[TF])-sum(TF)  
       
    t[i]=1
    imb_net_1=imbm(i,flag_imb) #imb_net=Im^2/n^2, Im converges with speed n^2
    imb_cov_1=w_o*(d_o+1)^2+w_m*(sum((d_1+1)^2))+w_s*((d_s+1)^2)
    im1=w*imb_cov_1+(1-w)*imb_net_1
    
    t[i]=0
    imb_net_2=imbm(i,flag_imb) #imb_net=Im^2/n^2, Im converges with speed n^2
    imb_cov_2=w_o*(d_o-1)^2+w_m*(sum((d_1-1)^2))+w_s*((d_s-1)^2)
    im2=w*imb_cov_2+(1-w)*imb_net_2

    if (im1-im2>-10 & im1-im2<0) {
      t[i]=rbinom(1,1,q)
      im_net[i]=imbm(i,flag_imb)
      im_cov[i]=w_o*(d_o+2*t[i]-1)^2+w_m*(sum((d_1+2*t[i]-1)^2))+w_s*((d_s+2*t[i]-1)^2)
      im[i]=w*im_cov[i]+(1-w)*im_net[i]
    }
    else if (im1-im2<10 & im1-im2>0 ) {
      t[i]= rbinom(1,1,1-q)
      im_net[i]=imbm(i,flag_imb)
      im_cov[i]=w_o*(d_o+2*t[i]-1)^2+w_m*(sum((d_1+2*t[i]-1)^2))+w_s*((d_s+2*t[i]-1)^2)
      im[i]=w*im_cov[i]+(1-w)*im_net[i]
    } 
    else if (im1-im2>=10 ) {
      qnew=ifelse(q==0.5, 0.5, 10/abs(im1-im2)^(2.1))
      t[i]=rbinom(1,1,qnew)
      im_net[i]=imbm(i,flag_imb)
      im_cov[i]=w_o*(d_o+2*t[i]-1)^2+w_m*(sum((d_1+2*t[i]-1)^2))+w_s*((d_s+2*t[i]-1)^2)
       im[i]=w*im_cov[i]+(1-w)*im_net[i]
      } 
    else if (im1-im2<=-10 ) {
      qnew=ifelse(q==0.5, 0.5, 10/abs(im1-im2)^(2.1))
      t[i]= rbinom(1,1,1-qnew)
      im_net[i]=imbm(i,flag_imb)
      im_cov[i]=w_o*(d_o+2*t[i]-1)^2+w_m*(sum((d_1+2*t[i]-1)^2))+w_s*((d_s+2*t[i]-1)^2)
       im[i]=w*im_cov[i]+(1-w)*im_net[i]
      } 
    else{
      t[i]= rbinom(1,1,0.5)
      im_net[i]=imbm(i,flag_imb)
      im_cov[i]=imb_cov_1[i]
      im[i]=w*im_cov[i]+(1-w)*im_net[i]
    }
    
     o_diff[i]=2*sum(t[1:i])-i      #sum(t)-(n-sum(t))
     
     for (j in 1:num_cov) {
      dd_1[j]=(2*sum(t[ddd[1:i,j]==1])-sum(ddd[1:i,j]==1))# margin difference D(j,1), jth cov at level=1, after n units assgned
      dd_0[j]=(2*sum(t[ddd[1:i,j]==0])-sum(ddd[1:i,j]==0))# margin difference D(j,0), jth cov at level=0, after n units assgned
      #dd_1 is a row, jth element=margin diff of jth covariate
      }
      dd_1x[i]=dd_1[1]  #dd_0x[i]=dd_0[1]  #dd_x1[i]=dd_1[2]
      dd_x0[i]=dd_0[2]
  
      for (l in 1:i) {
        TF11[l]=all(ddd[l,]==c(1,1))
        TF10[l]=all(ddd[l,]==c(1,0))
        TF01[l]=all(ddd[l,]==c(0,1))
        TF00[l]=all(ddd[l,]==c(0,0))
      }
      dd_s11[i]=sum(2*t[TF11])-sum(TF11)  #dd_s10[i]=sum(2*t[TF10])-sum(TF10)  #dd_s01[i]=sum(2*t[TF01])-sum(TF01)  
      dd_s00[i]=sum(2*t[TF00])-sum(TF00)  

 }#end n
  
  overall_diff=cbind(overall_diff, o_diff) #overimbalance of ith units have been assigned, n*M matrix,
  ddd_1x_diff=cbind(ddd_1x_diff,dd_1x)
  ddd_x0_diff=cbind(ddd_x0_diff,dd_x0)
  ddd_s11_diff=cbind(ddd_s11_diff,dd_s11)
  ddd_s00_diff=cbind(ddd_s00_diff,dd_s00)  
  
  IMM=cbind(IMM,im) # IMM is a n*N matrix, ith row represents nth units have been assigned, ith coloum is the result of ith simulation.
  IMM_net=cbind(IMM_net,im_net)
  IMM_cov=cbind(IMM_cov,im_cov)
  
  Er=rnorm(n,0,Error_sd)
  ResponseY=mu0+mu1*t+Ad%*%t+gamma_X1*X1+gamma_X2*X2+gamma_X1X2*X1*X2+Er

  Beta_G[k]=mean(ResponseY[t==1])-mean(ResponseY[t==0])
  
   print(k)
} #end repeat
  
```

```{r}
IMM_c=rowMeans(IMM, na.rm = TRUE, dims = 1)
IMM_net_c=rowMeans(IMM_net, na.rm = TRUE, dims = 1)
IMM_cov_c=rowMeans(IMM_cov, na.rm = TRUE, dims = 1)

overall_diff_c=rowMeans(abs(overall_diff), na.rm = TRUE, dims = 1)
overall_diff_sd_c=rowSds(overall_diff, na.rm = TRUE, dims = 1)

IMM_1x_c=rowMeans(abs(ddd_1x_diff), na.rm = TRUE, dims = 1)
IMM_1x_sd_c=rowSds(ddd_1x_diff, na.rm = TRUE, dims = 1)

IMM_x0_c=rowMeans(abs(ddd_x0_diff), na.rm = TRUE, dims = 1)
IMM_x0_sd_c=rowSds(ddd_x0_diff, na.rm = TRUE, dims = 1)

IMM_s11_c=rowMeans(abs(ddd_s11_diff), na.rm = TRUE, dims = 1)
IMM_s11_sd_c=rowSds(ddd_s11_diff, na.rm = TRUE, dims = 1)

IMM_s00_c=rowMeans(abs(ddd_s00_diff), na.rm = TRUE, dims = 1)
IMM_s00_sd_c=rowSds(ddd_s00_diff, na.rm = TRUE, dims = 1)

Bia_CAR=mean(Beta_G)-mu1
var_CAR=var(Beta_G)
```

# Output bias, standard deviation(sd), mes, network imbalance measures, and covariate imbalance measures
```{r}
#print('Imb')

### print('net imb')
IMM_net_c[n]

###
#print('overall cov imb sd')
overall_diff_c[n]

###
#print('marginal cov imb sd')
IMM_1x_c[n]
IMM_x0_c[n]

###
#print('stratum cov imb sd')
IMM_s11_c[n]
IMM_s00_c[n]

### Estimation
Bia_CAR
sqrt(var_CAR)
Bia_CAR^2+var_CAR
```

